python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone resnet18 --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone resnet18 --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone resnet18 --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone resnet18 --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone resnet18 --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone caffenet --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone caffenet --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone caffenet --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone caffenet --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone caffenet --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone vit_small --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone vit_small --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone vit_small --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone vit_small --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-all.yaml --backbone vit_small --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone resnet18 --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone resnet18 --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone resnet18 --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone resnet18 --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone resnet18 --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone caffenet --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone caffenet --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone caffenet --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone caffenet --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone caffenet --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone vit_small --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone vit_small --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone vit_small --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone vit_small --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-first.yaml --backbone vit_small --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone resnet18 --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone resnet18 --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone resnet18 --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone resnet18 --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone resnet18 --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone caffenet --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone caffenet --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone caffenet --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone caffenet --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone caffenet --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone vit_small --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone vit_small --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone vit_small --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone vit_small --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_imgaug_canny-second.yaml --backbone vit_small --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone resnet18 --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone resnet18 --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone resnet18 --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone resnet18 --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone resnet18 --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone caffenet --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone caffenet --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone caffenet --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone caffenet --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone caffenet --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone vit_small --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone vit_small --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone vit_small --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone vit_small --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original_canny.yaml --backbone vit_small --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone resnet18 --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone resnet18 --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone resnet18 --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone resnet18 --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone resnet18 --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone caffenet --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone caffenet --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone caffenet --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone caffenet --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone caffenet --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone vit_small --train_only photo --seed 0 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone vit_small --train_only photo --seed 1 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone vit_small --train_only photo --seed 2 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone vit_small --train_only photo --seed 3 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0
python method_jt.py --run experiments/yaml_PACS_original.yaml --backbone vit_small --train_only photo --seed 4 --method_loss 1 --lr 0.00154 --epochs 300 --dataset PACS --gpu 0